// Fallback STUN/TURN server (UDP only) for when coturn is not available, e.g. GitHub downloads are blocked.
// Intended for local testing. Use coturn on the real server (it also supports TURN over TCP/TLS).
//
// Usage: node turn-server.js --config=<path to json>
// The JSON file is generated by Deployment/Start-Stack.ps1.

const fs = require('fs');
const Turn = require('node-turn');

const configArg = process.argv.find((a) => a.startsWith('--config='));
if (!configArg) {
	console.error('Missing --config=<file>');
	process.exit(2);
}
const cfg = JSON.parse(fs.readFileSync(configArg.substring('--config='.length), 'utf8'));

const options = {
	listeningPort: cfg.port,
	listeningIps: [cfg.listenIp],
	relayIps: [cfg.listenIp],
	minPort: cfg.minPort,
	maxPort: cfg.maxPort,
	authMech: 'long-term',
	credentials: { [cfg.user]: cfg.password },
	realm: cfg.realm,
	debugLevel: cfg.debugLevel || 'INFO'
};
// Behind NAT: advertise the public IP for relay allocations.
if (cfg.externalIp && cfg.externalIp !== cfg.listenIp) {
	options.externalIps = cfg.externalIp;
}

const server = new Turn(options);
server.start();
console.log(`node-turn listening on udp ${cfg.listenIp}:${cfg.port}, relay ${cfg.minPort}-${cfg.maxPort}, realm ${cfg.realm}`);
